spring:
  profiles: test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: admin
    password: admin123!#
    initialization-mode: always
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        # 예약어 사용 가능
        globally_quoted_identifiers: true
logging:
  level:
    org.springframework.jdbc.core: DEBUG
