version: '2'
services:
  postgresql:
    container_name: postgresql
    image: postgres
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin123!#"
      POSTGRES_DB: "test"
