version: '2'
services:
  zookeeper:
    container_name: local-zookeeper
    image: wurstmeister/zookeeper:3.4.6
    restart: always
    ports:
      - "2181:2181"
  kafka-1:
    image: wurstmeister/kafka:2.12-2.2.0
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "32681:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_ADVERTISED_HOST_NAME: test.local.kafka01
      # 로그 유지 시간, 단위 ms
      KAFKA_LOG_RETENTION_MS: 10000
      # 로그 유지 시간 체크 간격, 단위 ms
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 2000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-2:
    image: wurstmeister/kafka:2.12-2.2.0
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "32682:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_ADVERTISED_HOST_NAME: test.local.kafka02
      # 로그 유지 시간, 단위 ms
      KAFKA_LOG_RETENTION_MS: 10000
      # 로그 유지 시간 체크 간격, 단위 ms
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 2000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
